version: "3.9"
x-redash-service: &redash-service
  image: redash/redash:8.0.0.b32245
  depends_on:
    - postgres
    - redis
  env_file: ./.env
services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5001:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  redis:
    image: redis:5.0-alpine
  postgres:
    image: postgres:9.6-alpine
    env_file: ./.env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  nginx:
    image: redash/nginx:latest
    platform: linux/amd64
    ports:
      - "8080:80"
    depends_on:
      - server
    links:
      - server:redash